import Foundation

/// A semantic key action generated by the app's UI, independent of the terminal engine
/// and independent of the escape sequences a particular mode requires.
public enum TerminalKeyAction: Equatable, Sendable, Hashable {
    case escape
    case tab
    case backTab
    case enter
    case backspace
    case forwardDelete
    case up
    case down
    case left
    case right
    case arrow(TerminalArrowDirection, modifiers: TerminalArrowModifiers)
    case home
    case end
    case pageUp
    case pageDown
    /// e.g. `.control("c")` encodes to `0x03`.
    case control(Character)
    /// F1...F12
    case function(Int)
}

/// Directions and modifiers supported by the software arrow controls.
public enum TerminalArrowDirection: String, Equatable, Sendable, Hashable {
    case up = "A"
    case down = "B"
    case right = "C"
    case left = "D"
}

public struct TerminalArrowModifiers: OptionSet, Sendable, Hashable {
    public let rawValue: Int

    public init(rawValue: Int) { self.rawValue = rawValue }

    public static let shift = Self(rawValue: 1)
    public static let option = Self(rawValue: 2)
}

/// Terminal modes that affect key encoding, for adapters that encode keys themselves with
/// `TerminalKeyEncoder` instead of delegating to their engine.
public struct TerminalModes: Equatable, Sendable {
    public var applicationCursor: Bool
    public var bracketedPaste: Bool
    public var backspaceSendsControlH: Bool

    public init(
        applicationCursor: Bool = false,
        bracketedPaste: Bool = false,
        backspaceSendsControlH: Bool = false
    ) {
        self.applicationCursor = applicationCursor
        self.bracketedPaste = bracketedPaste
        self.backspaceSendsControlH = backspaceSendsControlH
    }
}

/// Encodes semantic key actions and pasted text into the xterm-compatible byte sequences
/// a terminal engine expects, so screens never hard-code escape sequences.
public enum TerminalKeyEncoder {
    private static let esc: UInt8 = 0x1b

    /// Returns the bytes to send for a semantic key given the terminal's current modes.
    /// Returns empty `Data` for an unencodable control character or an out-of-range function key.
    public static func encode(_ action: TerminalKeyAction, modes: TerminalModes) -> Data {
        switch action {
        case .escape:
            return Data([esc])
        case .tab:
            return Data([0x09])
        case .backTab:
            return csi("Z")
        case .enter:
            return Data([0x0d])
        case .backspace:
            return Data([modes.backspaceSendsControlH ? 0x08 : 0x7f])
        case .forwardDelete:
            return csi("3~")
        case .up:
            return cursor("A", modes: modes)
        case .down:
            return cursor("B", modes: modes)
        case .right:
            return cursor("C", modes: modes)
        case .left:
            return cursor("D", modes: modes)
        case .arrow(let direction, let modifiers):
            if modifiers.isEmpty { return cursor(direction.rawValue, modes: modes) }
            let parameter = 1 + (modifiers.contains(.shift) ? 1 : 0) + (modifiers.contains(.option) ? 2 : 0)
            return csi("1;\(parameter)\(direction.rawValue)")
        case .home:
            return cursor("H", modes: modes)
        case .end:
            return cursor("F", modes: modes)
        case .pageUp:
            return csi("5~")
        case .pageDown:
            return csi("6~")
        case .control(let character):
            guard let byte = controlByte(for: character) else { return Data() }
            return Data([byte])
        case .function(let n):
            return encodeFunction(n)
        }
    }

    /// Wraps pasted text in bracketed-paste markers when the mode is enabled; always normalizes
    /// "\r\n" and "\n" to "\r" (terminals expect CR for Return) — EXCEPT when bracketed paste is
    /// enabled, in which case the text is kept verbatim inside the markers.
    public static func encodePaste(_ text: String, modes: TerminalModes) -> Data {
        if modes.bracketedPaste {
            var data = csi("200~")
            data.append(contentsOf: Array(text.utf8))
            data.append(csi("201~"))
            return data
        }
        let normalized = text
            .replacingOccurrences(of: "\r\n", with: "\r")
            .replacingOccurrences(of: "\n", with: "\r")
        return Data(normalized.utf8)
    }

    /// Applies a one-shot Ctrl to typed input: a single character with a control code becomes
    /// that code, and anything else (Return, emoji, multi-character input) passes through unchanged.
    public static func applyingControl(to typed: Data) -> Data {
        guard let text = String(data: typed, encoding: .utf8), text.count == 1,
              let character = text.first, let byte = controlByte(for: character) else { return typed }
        return Data([byte])
    }

    /// xterm's control codes, including the digit and `/` aliases (Ctrl+2 is NUL, Ctrl+/ is 0x1f).
    public static func controlByte(for character: Character) -> UInt8? {
        switch character {
        case "@", " ", "2":
            return 0x00
        case "[", "3":
            return 0x1b
        case "\\", "4":
            return 0x1c
        case "]", "5":
            return 0x1d
        case "^", "6":
            return 0x1e
        case "_", "/", "7":
            return 0x1f
        case "?", "8":
            return 0x7f
        default:
            guard let ascii = character.asciiValue else { return nil }
            let upper = (ascii >= 0x61 && ascii <= 0x7a) ? ascii - 0x20 : ascii
            guard upper >= 0x40 && upper <= 0x5f else { return nil }
            return upper & 0x1f
        }
    }

    private static func csi(_ suffix: String) -> Data {
        var data = Data([esc, UInt8(ascii: "[")])
        data.append(contentsOf: Array(suffix.utf8))
        return data
    }

    private static func ss3(_ suffix: String) -> Data {
        var data = Data([esc, UInt8(ascii: "O")])
        data.append(contentsOf: Array(suffix.utf8))
        return data
    }

    private static func cursor(_ suffix: String, modes: TerminalModes) -> Data {
        modes.applicationCursor ? ss3(suffix) : csi(suffix)
    }

    private static func encodeFunction(_ n: Int) -> Data {
        switch n {
        case 1: return ss3("P")
        case 2: return ss3("Q")
        case 3: return ss3("R")
        case 4: return ss3("S")
        case 5: return csi("15~")
        case 6: return csi("17~")
        case 7: return csi("18~")
        case 8: return csi("19~")
        case 9: return csi("20~")
        case 10: return csi("21~")
        case 11: return csi("23~")
        case 12: return csi("24~")
        default: return Data()
        }
    }
}
